#!/usr/bin/env node
/**
 * send-email.js
 *
 * PNGを添付してメール送信する。
 * SendGrid（推奨）または Gmail + Nodemailer に対応。
 *
 * 環境変数:
 *   SENDGRID_API_KEY  - SendGrid APIキー（SendGrid使用時）
 *   GMAIL_USER        - Gmailアドレス（Gmail使用時）
 *   GMAIL_APP_PASS    - GmailアプリパスワードorOAuth（Gmail使用時）
 *   MAIL_TO           - 宛先メールアドレス（複数はカンマ区切り）
 *   MAIL_FROM         - 送信元メールアドレス
 *   MAIL_SUBJECT      - 件名（省略時は自動生成）
 *
 * Usage: node src/send-email.js [--provider sendgrid|gmail]
 */

const fs = require('fs');
const path = require('path');

const OUTPUT_DIR = path.join(__dirname, '../output');
const ARTICLES_PATH = path.join(OUTPUT_DIR, 'articles.json');

function getSubject() {
  if (process.env.MAIL_SUBJECT) return process.env.MAIL_SUBJECT;

  const now = new Date(Date.now() + 9 * 60 * 60 * 1000); // JST
  const dateStr = `${now.getUTCFullYear()}/${now.getUTCMonth() + 1}/${now.getUTCDate()}`;
  return `【ニュースダイジェスト】${dateStr} 原油・プラスチック・小売・包装資材`;
}

function buildTextBody(data) {
  const digestUrl = process.env.DIGEST_URL || '';
  if (!data) return `ニュースダイジェストをご確認ください。\n${digestUrl}`;

  const { categories, windowStart, windowEnd } = data;
  const s = new Date(windowStart);
  const e = new Date(windowEnd);
  const toJST = (d) => {
    const j = new Date(d.getTime() + 9 * 60 * 60 * 1000);
    return `${j.getUTCMonth() + 1}/${j.getUTCDate()} ${String(j.getUTCHours()).padStart(2, '0')}:00`;
  };

  let body = `ニュースダイジェスト\n`;
  body += `対象期間: ${toJST(s)} 〜 ${toJST(e)} JST\n`;

  if (digestUrl) {
    body += `\n▶ 全文・AI要約はこちら\n${digestUrl}\n`;
  }

  body += `\n${'─'.repeat(40)}\n`;

  for (const [, category] of Object.entries(categories)) {
    body += `\n【${category.label}】 ${category.articles.length}件\n`;
    if (category.trendSummary) {
      body += `今日のまとめ: ${category.trendSummary}\n`;
    }
    for (const a of category.articles.slice(0, 3)) {
      body += `・${a.title}\n`;
    }
    if (category.articles.length > 3) {
      body += `  …他${category.articles.length - 3}件\n`;
    }
  }

  body += '\n---\nNews Digest - 自動配信 / Generated by Claude Code\n';
  return body;
}

function buildHtmlBody(data) {
  const digestUrl = process.env.DIGEST_URL || '';

  const toJST = (d) => {
    const j = new Date(new Date(d).getTime() + 9 * 60 * 60 * 1000);
    return `${j.getUTCMonth() + 1}/${j.getUTCDate()} ${String(j.getUTCHours()).padStart(2, '0')}:00`;
  };

  const windowLabel = data
    ? `${toJST(data.windowStart)} 〜 ${toJST(data.windowEnd)} JST`
    : '';

  const totalArticles = data
    ? Object.values(data.categories).reduce((s, c) => s + c.articles.length, 0)
    : 0;

  const categoryRows = data
    ? Object.entries(data.categories).map(([, c]) => {
        const trend = c.trendSummary
          ? `<p style="margin:6px 0 0;font-size:13px;color:#475569;line-height:1.6;">${c.trendSummary}</p>`
          : '';
        return `<tr>
          <td style="padding:12px 0;border-bottom:1px solid #e2e8f0;vertical-align:top;">
            <strong style="font-size:14px;color:#1e293b;">${c.label}</strong>
            <span style="font-size:12px;color:#94a3b8;margin-left:8px;">${c.articles.length}件</span>
            ${trend}
          </td>
        </tr>`;
      }).join('\n')
    : '';

  const urlBlock = digestUrl
    ? `<div style="margin:24px 0;text-align:center;">
        <a href="${digestUrl}" style="display:inline-block;padding:12px 28px;background:#0f172a;color:#fff;text-decoration:none;border-radius:8px;font-size:14px;font-weight:600;">
          全記事・AI要約を読む →
        </a>
        <p style="margin:8px 0 0;font-size:11px;color:#94a3b8;">${digestUrl}</p>
      </div>`
    : '';

  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Hiragino Sans',sans-serif;">
<div style="max-width:560px;margin:0 auto;padding:32px 16px;">

  <div style="background:#fff;border-radius:12px;border:1px solid #e2e8f0;overflow:hidden;">
    <div style="background:#0f172a;padding:20px 24px;">
      <h1 style="margin:0;font-size:18px;font-weight:700;color:#fff;">ニュースダイジェスト</h1>
      <p style="margin:4px 0 0;font-size:12px;color:#94a3b8;">${windowLabel}</p>
    </div>

    <div style="padding:24px;">
      <p style="margin:0 0 4px;font-size:13px;color:#64748b;">本日の収集記事</p>
      <p style="margin:0 0 20px;font-size:28px;font-weight:700;color:#0f172a;">${totalArticles}<span style="font-size:14px;font-weight:400;color:#94a3b8;margin-left:4px;">件</span></p>

      ${urlBlock}

      <table style="width:100%;border-collapse:collapse;">
        ${categoryRows}
      </table>

      <p style="margin:20px 0 0;font-size:11px;color:#cbd5e1;text-align:center;">Generated by Claude Code</p>
    </div>
  </div>

</div>
</body>
</html>`;
}

function getPngAttachments() {
  if (!fs.existsSync(OUTPUT_DIR)) return [];

  return fs
    .readdirSync(OUTPUT_DIR)
    .filter((f) => f.endsWith('.png') && f.startsWith('digest-'))
    .sort()
    .map((f) => ({
      filename: f,
      path: path.join(OUTPUT_DIR, f),
    }));
}

async function sendWithSendGrid(options) {
  const sgMail = require('@sendgrid/mail');
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);

  const toAddresses = options.to.split(',').map((s) => s.trim());

  const attachments = options.attachments.map((att) => ({
    content: fs.readFileSync(att.path).toString('base64'),
    filename: att.filename,
    type: 'image/png',
    disposition: 'attachment',
  }));

  const msg = {
    to: toAddresses,
    from: options.from,
    subject: options.subject,
    text: options.text,
    html: options.html,
    attachments,
  };

  await sgMail.send(msg);
  console.log(`SendGrid: 送信完了 → ${toAddresses.join(', ')}`);
}

async function sendWithGmail(options) {
  // nodemailer は GitHub Actions 環境で別途インストールが必要
  // Gmail 使用時は package.json に nodemailer を追加すること
  let nodemailer;
  try {
    nodemailer = require('nodemailer');
  } catch {
    console.error('nodemailer がインストールされていません。');
    console.error('Gmail を使用する場合: npm install nodemailer');
    process.exit(1);
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASS,
    },
  });

  const attachments = options.attachments.map((att) => ({
    filename: att.filename,
    path: att.path,
  }));

  await transporter.sendMail({
    from: options.from,
    to: options.to,
    subject: options.subject,
    text: options.text,
    html: options.html,
    attachments,
  });

  console.log(`Gmail: 送信完了 → ${options.to}`);
}

async function main() {
  const args = process.argv.slice(2);
  const providerIdx = args.indexOf('--provider');
  let provider = providerIdx !== -1 ? args[providerIdx + 1] : null;

  // 自動判定
  if (!provider) {
    if (process.env.SENDGRID_API_KEY) provider = 'sendgrid';
    else if (process.env.GMAIL_USER && process.env.GMAIL_APP_PASS) provider = 'gmail';
    else {
      console.error('メール送信プロバイダーが設定されていません。');
      console.error('SENDGRID_API_KEY または GMAIL_USER + GMAIL_APP_PASS を設定してください。');
      process.exit(1);
    }
  }

  const to = process.env.MAIL_TO;
  const from = process.env.MAIL_FROM;

  if (!to || !from) {
    console.error('MAIL_TO と MAIL_FROM 環境変数が必要です。');
    process.exit(1);
  }

  let articlesData = null;
  if (fs.existsSync(ARTICLES_PATH)) {
    try {
      articlesData = JSON.parse(fs.readFileSync(ARTICLES_PATH, 'utf8'));
    } catch (parseErr) {
      console.warn(`[WARN] articles.json の読み込みに失敗しました: ${parseErr.message}`);
    }
  }

  const digestUrl = process.env.DIGEST_URL || '';
  if (digestUrl) {
    console.log(`ダイジェストURL: ${digestUrl}`);
  } else {
    console.warn('[WARN] DIGEST_URL が設定されていません。URLなしで送信します。');
  }

  const options = {
    to,
    from,
    subject: getSubject(),
    text: buildTextBody(articlesData),
    html: buildHtmlBody(articlesData),
    attachments: [],
  };

  console.log(`\n=== メール送信 ===`);
  console.log(`プロバイダー: ${provider}`);
  console.log(`件名: ${options.subject}`);
  console.log(`宛先: ${to}`);

  try {
    if (provider === 'sendgrid') {
      await sendWithSendGrid(options);
    } else if (provider === 'gmail') {
      await sendWithGmail(options);
    } else {
      console.error(`未対応のプロバイダー: ${provider}`);
      process.exit(1);
    }
  } catch (err) {
    console.error('送信エラー:', err.message || err);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('未処理エラー:', err.message || err);
  process.exit(1);
});
